version: '3.8'

networks:
  boring:
    external: true

services:
  discord-alert:
    build: .
    image: discord-alert
    container_name: discord-alert
    networks:
      - boring
    env_file:
      - .env
    restart: unless-stopped 