services:
  api:
    build: .
    image: base-node-pg
    container_name: base-node-pg
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - boring
    restart: unless-stopped

networks:
  boring:
    external: true
